---
title: "Etsy Interactive Sales Map"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE}
library(shiny)
library(readr)
library(plotly)

#htmltools::tags$iframe(
#  width = "1024",
#  height = "768",
#  src = "USMAP.html", 
#  scrolling = "no", 
#  seamless = "seamless",
#  frameBorder = "0"#,
  #style="-webkit-transform:scale(0.5);-moz-transform-scale(0.5);"
#)

```



```{r}
plotTable <- read_csv(here::here("ShinyMap/plotTable.csv"))
plotTable

# Define UI --------------------------------------------------------------------

ui <- fluidPage(
    br(),
    
    sidebarLayout(
        sidebarPanel(
            dateRangeInput("daterange3", "Date range:",
                           start  = "2021-07-31",
                           end    = "2021-10-08",
                           min    = "2021-07-31",
                           max    = "2021-10-08",
                           format = "mm/dd/yy",
                           separator = " - ")
            
        ),
        
        mainPanel(
            plotlyOutput(outputId = "map")
           
        )
    )
)

# Define server ----------------------------------------------------------------

server <- function(input, output, session) {
    
    output$testTable <- renderTable({
        fullTable <- plotTable %>% 
            filter(sellDay >= input$daterange3[1] & sellDay<= input$daterange3[2]) %>%
            group_by(statesOver) %>% 
            summarise(sellDay, statesOver, items, newCumulative = cumsum(items))
    })
    
    
    output$map <- renderPlotly({
        fullTable <- plotTable %>% 
            filter(sellDay >= input$daterange3[1] & sellDay<= input$daterange3[2]) %>%
            group_by(statesOver) %>% 
            summarise(sellDay, statesOver, items, newCumulative = cumsum(items))
        
        fullTable <- fullTable %>% 
            mutate(logSold=ifelse(newCumulative>0, log(newCumulative+1), 0))
        
        USMAP <- fullTable %>% 
            filter(sellDay >= input$daterange3[1]) %>% 
            plot_ly(
                type = 'choropleth',
                locations= ~statesOver,
                locationmode = 'USA-states' , 
                colorscale='tempo', z=~logSold,
                zmin=0, zmax=6,
                text=~newCumulative,
                hoverinfo='text',
                showscale=FALSE,
                frame=~as.Date(sellDay)) %>% 
            layout(geo=list( scope = 'usa' )) 
        
       
    })
}

# Create the Shiny app object --------------------------------------------------

shinyApp(ui = ui, server = server, options = list(width = "100%", height = 700))
```

